# Bulk Download Data with `earthaccess`

Whew – we’ve processed some reflectance data! But you may have noticed
that your image doesn’t include all of Denver, or all the spectral bands
you will need – Your search returned 60 different files covering
different spectral bands and spatial areas! To work with all of them, we
will have to utilize **DRY** coding techniques – `for` loops and
functions.

First things first – load your stored variables into memory:

In [2]:
%store -r denver_redlining_gdf data_dir

<link rel="stylesheet" type="text/css" href="./assets/styles.css"><div class="callout callout-style-default callout-titled callout-task"><div class="callout-header"><div class="callout-icon-container"><i class="callout-icon"></i></div><div class="callout-title-container flex-fill">Try It: Import packages</div></div><div class="callout-body-container callout-body"><p>Add imports for packages that help you:</p>
<ol type="1">
<li>Work with the file system interoperably</li>
<li>Work with vector data</li>
<li>Create interactive plots of vector data</li>
<li>Group and aggregate tabular data</li>
</ol></div></div>

In [3]:
# Interoperable file paths
import os
import pathlib
import re # Use regular expressions to extract metadata

import geopandas as gpd 
import matplotlib.pyplot as plt
import hvplot.pandas

import earthaccess # Access NASA data from the cloud
# Overlay plots
import numpy as np # Process bit-wise cloud mask
import pandas as pd
# Group and aggregate
# Work with raster data
import rioxarray as rxr
from rioxarray.merge import merge_arrays # Merge rasters
import cartopy.crs as ccrs # CRSs

<link rel="stylesheet" type="text/css" href="./assets/styles.css"><div class="callout callout-style-default callout-titled callout-task"><div class="callout-header"><div class="callout-icon-container"><i class="callout-icon"></i></div><div class="callout-title-container flex-fill">Try It: Set up `earthaccess` connection</div></div><div class="callout-body-container callout-body"><p>As you did before, log in to your <code>earthaccess</code> account,
search for the Denver data, and open the file connections. You will find
that you have to re-run your search every time you access a file – keep
this in mind if you get errors later!</p></div></div>

In [4]:
# login
earthaccess.login(strategy="interactive", persist=True)

In [5]:
# Search earthaccess

denver_results = earthaccess.search_data(
    short_name="HLSL30",
    bounding_box=tuple(denver_redlining_gdf.total_bounds),
    temporal=("2023-07-11"),
    count=1 # return a single data granule
)

hls_data = earthaccess.open(denver_results)
hls_data

QUEUEING TASKS | :   0%|          | 0/15 [00:00<?, ?it/s]

PROCESSING TASKS | :   0%|          | 0/15 [00:00<?, ?it/s]

COLLECTING RESULTS | :   0%|          | 0/15 [00:00<?, ?it/s]

[<File-like object HTTPFileSystem, https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/HLSL30.020/HLS.L30.T13TEE.2023192T174310.v2.0/HLS.L30.T13TEE.2023192T174310.v2.0.B05.tif>,
 <File-like object HTTPFileSystem, https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/HLSL30.020/HLS.L30.T13TEE.2023192T174310.v2.0/HLS.L30.T13TEE.2023192T174310.v2.0.VAA.tif>,
 <File-like object HTTPFileSystem, https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/HLSL30.020/HLS.L30.T13TEE.2023192T174310.v2.0/HLS.L30.T13TEE.2023192T174310.v2.0.B10.tif>,
 <File-like object HTTPFileSystem, https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/HLSL30.020/HLS.L30.T13TEE.2023192T174310.v2.0/HLS.L30.T13TEE.2023192T174310.v2.0.B06.tif>,
 <File-like object HTTPFileSystem, https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/HLSL30.020/HLS.L30.T13TEE.2023192T174310.v2.0/HLS.L30.T13TEE.2023192T174310.v2.0.B03.tif>,
 <File-like object HTTPFileSystem, https://data.lpdaac.earth

## Putting it all together

To get a complete image, we will have to:

1.  Load in all 4 rasters that cover Denver
2.  Process them
3.  Merge, or mosaic, them into one image

And…we haven’t even talked about the other bands you might need, or what
to do if you want a time-series of images. You can see that if we were
to copy and paste all the code above for each raster we need to load, it
could get pretty overwhelming, and *very* error-prone. This is the
opposite of what we mean by **DRY** (Don’t Repeat Yourself) code.

Before we continue, we’re going to make some functions to do the tasks
you completed up above. We’ve already set up the code for you,
identified **parameters** and **returns**, and added **docstrings** to
document your function. When writing a function, we recommend the
following process:

1.  Copy the code you’re using into the function shell, making sure to
    indent it so Python knows it is part of the function.
2.  Identify any variables that are **too specific**. For example, if I
    called a `DataArray` `denver_da`, but I could use my function to
    process data from anywhere…I might change the name to `da` whereever
    it appears.
3.  Identify the function **parameters** or arguments and make sure they
    match your code. Python may let you, but we recommend not using
    variables defined outside the function inside the function – if you
    need something in your function make sure to pass it in as a
    parameter!
4.  Identify the function **returns** and make sure they match your
    code. What do you want to be able to access at the end? Keep in mind
    that unless you return them, the variables you create in a function
    will be stuck there. The `return` statement at the end of your
    function will pass the variables you want to keep back out of the
    function.
5.  Write some code to test your function, such as by plotting the
    results. We recommend going line by line when you’re just getting
    started. This usually involves commenting code later on, and
    modifying the returns and test code as you go.
6.  Restart the kernel and run your function to check that doesn’t have
    any hidden requirements.

<link rel="stylesheet" type="text/css" href="./assets/styles.css"><div class="callout callout-style-default callout-titled callout-task"><div class="callout-header"><div class="callout-icon-container"><i class="callout-icon"></i></div><div class="callout-title-container flex-fill">Try It: DRY code with functions</div></div><div class="callout-body-container callout-body"><p>Take each processing step from above, and create a function to do it.
We recommend writing the following 2 functions:</p>
<ol type="1">
<li>A function to load a raster, crop it, and apply the scale
factor</li>
<li>A function to process the cloud mask</li>
</ol>
<p>Applying the cloud mask is a single line of code, so we don’t think
it needs its own function.</p>
<p>Make sure to test all your functions using your example from up
top!</p></div></div>

In [6]:
def process_image(uri, bounds_gdf):
    """
    Load, crop, and scale a raster image from earthaccess

    Parameters
    ----------
    uri: file-like or path-like
      File accessor downloaded or obtained from earthaccess
    bounds_gdf: gpd.GeoDataFrame
      Area of interest to crop to

    Returns
    -------
    cropped_da: rxr.DataArray
      Processed raster
    """
    # load and scale
    da = rxr.open_rasterio(uri, mask_and_scale=True).squeeze()

    # obtain crs from raster
    reflectance_data_crs = da.rio.crs

    # match coordinate reference systems
    bounds_gdf = bounds_gdf.to_crs(reflectance_data_crs)

    # get study bounds da
    study_bounds = bounds_gdf.total_bounds

    # crop
    cropped_da = da.rio.clip_box(
      minx=study_bounds[0], 
      miny=study_bounds[1], 
      maxx=study_bounds[2], 
      maxy=study_bounds[3]
    )

    return cropped_da

In [11]:
# Find a green layer path
green_path = hls_data[4] # B03 = green

cropped_image = process_image(green_path, denver_redlining_gdf)

In [111]:
def process_cloud_mask(cloud_uri, bits_to_mask):
    """
    Load an 8-bit Fmask file and process to a boolean mask

    Parameters
    ----------
    uri: file-like or path-like
      Fmask file accessor downloaded or obtained from earthaccess
    bits_to_mask: list of int
      The indices of the bits to mask if set

    Returns
    -------
    cloud_mask: np.array
      Cloud mask
    """
    cloud_da = rxr.open_rasterio(cloud_uri, mask_and_scale=True).squeeze()

    # Get the cloud mask as bits
    cloud_bits = (
        np.unpackbits(
            (
                # Get the cloud mask as an array...
                cloud_da.values
                # ... of 8-bit integers
                .astype('uint8')
                # With an extra axis to unpack the bits into
                [:, :, np.newaxis]
            ), 
            # List the least significat bit first to match the user guide
            bitorder='little',
            # Expand the array in a new dimension
            axis=-1)
    )
    
    # Add up the bits for each pixel
    cloud_mask = np.sum(
        # Select bits 
        cloud_bits[:,:,bits_to_mask], 
        # Sum along the bit axis
        axis=-1
    )

    # Mask the pixel if the sum is greater than 0
    # (If any of the bits are True)
    cloud_mask = cloud_mask == 0

    return cloud_mask

In [112]:
# find cloud Fmask
cloud_path = hls_data[8] # Fmask

bits_to_mask = [
    1, # Cloud
    2, # Adjacent to cloud
    3, # Cloud shadow
    5 # Water (to not confuse with greenspace)
]

In [113]:
denver_cloud_mask = process_cloud_mask(cloud_path, bits_to_mask)
denver_cloud_mask

/var/folders/t3/h1jr9k717rsd7qwky1jw1bz00000gn/T/ipykernel_1171/1944118658.py:26: RuntimeWarning: invalid value encountered in cast
  .astype('uint8')


array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

Our next new tool to help you write DRY and correct code is the regular
expression. Regular expressions are a little like the patterns we use
with `glob` that contain wildcard characters (`*`) – but, they are
**much** more powerful. With regular expressions, we can extract
different segments from a string (file name, in this case) based on
landmarks – even if those segments are not always the same length!

First – run another `earthaccess` search, this time removing the
`count=1` argument, or setting it to `count=-1`. This will include all
the results.

In [68]:
# Search earthaccess
denver_all_granules = earthaccess.search_data(
    short_name="HLSL30",
    bounding_box=tuple(denver_redlining_gdf.total_bounds),
    temporal=("2023-07-11"),
    count=-1 # return all data granules
)
print(len(denver_all_granules))

484


In [70]:
first_dataset = denver_all_granules[0]
print(first_dataset)

Collection: {'EntryTitle': 'HLS Landsat Operational Land Imager Surface Reflectance and TOA Brightness Daily Global 30m v2.0'}
Spatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'GPolygons': [{'Boundary': {'Points': [{'Longitude': -104.87957517, 'Latitude': 39.66154453}, {'Longitude': -104.54816965, 'Latitude': 40.64997256}, {'Longitude': -105.00023656, 'Latitude': 40.65085652}, {'Longitude': -105.00023316, 'Latitude': 39.66160696}, {'Longitude': -104.87957517, 'Latitude': 39.66154453}]}}]}}}
Temporal coverage: {'RangeDateTime': {'BeginningDateTime': '2023-07-11T17:43:10.669Z', 'EndingDateTime': '2023-07-11T17:43:10.669Z'}}
Size(MB): 44.883484840393066
Data: ['https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/HLSL30.020/HLS.L30.T13TEE.2023192T174310.v2.0/HLS.L30.T13TEE.2023192T174310.v2.0.B05.tif', 'https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/HLSL30.020/HLS.L30.T13TEE.2023192T174310.v2.0/HLS.L30.T13TEE.2023192T174310.v2.0.VAA.tif', 'https://data.l

In [8]:
# Open all earthaccess results
all_hls_data = earthaccess.open(denver_all_granules)
all_hls_data

QUEUEING TASKS | :   0%|          | 0/7260 [00:00<?, ?it/s]

PROCESSING TASKS | :   0%|          | 0/7260 [00:00<?, ?it/s]

COLLECTING RESULTS | :   0%|          | 0/7260 [00:00<?, ?it/s]

[<File-like object HTTPFileSystem, https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/HLSL30.020/HLS.L30.T13TEE.2023192T174310.v2.0/HLS.L30.T13TEE.2023192T174310.v2.0.B05.tif>,
 <File-like object HTTPFileSystem, https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/HLSL30.020/HLS.L30.T13TEE.2023192T174310.v2.0/HLS.L30.T13TEE.2023192T174310.v2.0.VAA.tif>,
 <File-like object HTTPFileSystem, https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/HLSL30.020/HLS.L30.T13TEE.2023192T174310.v2.0/HLS.L30.T13TEE.2023192T174310.v2.0.B10.tif>,
 <File-like object HTTPFileSystem, https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/HLSL30.020/HLS.L30.T13TEE.2023192T174310.v2.0/HLS.L30.T13TEE.2023192T174310.v2.0.B06.tif>,
 <File-like object HTTPFileSystem, https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/HLSL30.020/HLS.L30.T13TEE.2023192T174310.v2.0/HLS.L30.T13TEE.2023192T174310.v2.0.B03.tif>,
 <File-like object HTTPFileSystem, https://data.lpdaac.earth

<link rel="stylesheet" type="text/css" href="./assets/styles.css"><div class="callout callout-style-default callout-titled callout-task"><div class="callout-header"><div class="callout-icon-container"><i class="callout-icon"></i></div><div class="callout-title-container flex-fill">Try It: Get metadata with **regular expressions**</div></div><div class="callout-body-container callout-body"><p>Using the code below as a starting point, extract metadata from file
names and put them into a <code>DataFrame</code>. This strategy will
help you later on because you will be able to group rasters by their
metadata values, such as tile ID, band ID, and/or date.</p>
<ol type="1">
<li>Build your regular expression. ChatGPT is a great tool to get
started with your regular expression. You can also check out <a
href="https://regex101.com/">https://regex101.com/</a> to test your
regular expressions, making sure to select the <code>Python</code>
regular expression engine.</li>
<li>Replace file_name with a <strong>string</strong> version of the URI.
You can access it from the object you got from <code>earthaccess</code>
through the <code>.full_name</code> attribute.</li>
<li>Add the URIs from <code>earthaccess</code> to the
<code>DataFrame</code> you created as a new column.</li>
</ol></div></div>

In [84]:
# Compile a regular expression to search for metadata
# Use () to select the file name ending with .tif and only output that group
uri_re = re.compile(
    r"v2.0/(HLS.L30.*.tif)"
)
# select unique granules
tile_id_re = re.compile(
    r"HLSL30.020/(HLS.L30..*.v2.0)/HLS"
)
band_id_re = re.compile(
    r"HLS.L30..*v2.0.(\D{1}.*).tif"
)

# Find all the metadata in the file name 
uri_groups = []

for idx, uri in enumerate(all_hls_data):
    if (hasattr(uri, 'full_name')):
        file_name = uri_re.findall(uri.full_name)[0]
        tile_id = tile_id_re.findall(uri.full_name)[0]
        band_id = band_id_re.findall(uri.full_name)[0]
        

        uri_groups.append({
            'filename': file_name,
            'tile_id': tile_id,
            'band_id': band_id,
            'uri': uri
        })

# Create a DataFrame with the File-like URI
raster_df = pd.DataFrame(data=uri_groups, columns=['filename', 'tile_id', 'band_id', 'uri'])

# Only keep spectral bands and cloud Fmask
exclude_files = ['VAA', 'VZA', 'SAA', 'SZA']
raster_df = raster_df[~raster_df['band_id'].isin(exclude_files)]

# Check the results
raster_df.head()

filename  \
0  HLS.L30.T13TEE.2023192T174310.v2.0.B05.tif   
2  HLS.L30.T13TEE.2023192T174310.v2.0.B10.tif   
3  HLS.L30.T13TEE.2023192T174310.v2.0.B06.tif   
4  HLS.L30.T13TEE.2023192T174310.v2.0.B03.tif   
5  HLS.L30.T13TEE.2023192T174310.v2.0.B02.tif   

                              tile_id band_id  \
0  HLS.L30.T13TEE.2023192T174310.v2.0     B05   
2  HLS.L30.T13TEE.2023192T174310.v2.0     B10   
3  HLS.L30.T13TEE.2023192T174310.v2.0     B06   
4  HLS.L30.T13TEE.2023192T174310.v2.0     B03   
5  HLS.L30.T13TEE.2023192T174310.v2.0     B02   

                                                 uri  
0  <File-like object HTTPFileSystem, https://data...  
2  <File-like object HTTPFileSystem, https://data...  
3  <File-like object HTTPFileSystem, https://data...  
4  <File-like object HTTPFileSystem, https://data...  
5  <File-like object HTTPFileSystem, https://data...

In [114]:
# for each band 
    # for each tile (to merge the tiles in each band together later)

# 484 unique granules
# tile_groups = raster_df.groupby('tile_id')

bits_to_mask = [
    1, # Cloud
    2, # Adjacent to cloud
    3, # Cloud shadow
    5 # Water (to not confuse with greenspace)
]

# 484 unique granules
tile_groups = raster_df.groupby('tile_id')

for tile_name, tile_df in tile_groups:
    # test 
    if tile_name == 'HLS.L30.T13TEE.2023192T174310.v2.0':
        # Grab Fmask row from tile group
        Fmask_row = tile_df.loc[tile_df['band_id'] == 'Fmask']
        # Load the cloud mask
        cloud_path = Fmask_row.uri.values[0]
        cloud_mask = process_cloud_mask(cloud_path, bits_to_mask)

        # Load spectral bands
        band_groups = raster_df.groupby('band_id')
        for band_name, band_df in band_groups:
            if band_name != 'Fmask':
                # test 
                if band_name == 'B11':
                    print(band_name)
                    # keep 
                    for index, row in tile_df.iterrows():
                        # Process band
                        cropped_da = process_image(row.uri, denver_redlining_gdf)

                        # Mask band 
                        cloud_masked_da = cropped_da.where(~cropped_da.isin(cloud_mask))
                        display(cloud_masked_da)



/var/folders/t3/h1jr9k717rsd7qwky1jw1bz00000gn/T/ipykernel_1171/1944118658.py:26: RuntimeWarning: invalid value encountered in cast
  .astype('uint8')


B11


<xarray.DataArray (y: 480, x: 355)> Size: 682kB
array([[0.20619999, 0.1936    , 0.1696    , ..., 0.4122    , 0.46739998,
        0.41979998],
       [0.1873    , 0.20019999, 0.18169999, ..., 0.34899998, 0.4197    ,
        0.3773    ],
       [0.2342    , 0.2189    , 0.1774    , ..., 0.2812    , 0.32119998,
        0.2882    ],
       ...,
       [0.2724    , 0.24919999, 0.2333    , ...,        nan,        nan,
               nan],
       [0.2579    , 0.24219999, 0.2348    , ...,        nan,        nan,
               nan],
       [0.2629    , 0.2499    , 0.2226    , ...,        nan,        nan,
               nan]], dtype=float32)
Coordinates:
    band         int64 8B 1
  * x            (x) float64 3kB 5e+05 5e+05 5.001e+05 ... 5.106e+05 5.106e+05
  * y            (y) float64 4kB 4.405e+06 4.405e+06 ... 4.39e+06 4.39e+06
    spatial_ref  int64 8B 0
Attributes: (12/33)
    ACCODE:                    Lasrc
    arop_ave_xshift(meters):   0
    arop_ave_yshift(meters):   0
    arop_ncp:                  0
    arop_rmse(meters):         0
    arop_s2_refimg:            NONE
    ...                        ...
    TIRS_SSM_MODEL:            FINAL
    TIRS_SSM_POSITION_STATUS:  ESTIMATED
    ULX:                       499980
    ULY:                       4500000
    USGS_SOFTWARE:             LPGS_16.3.0
    AREA_OR_POINT:             Area

<xarray.DataArray (y: 480, x: 355)> Size: 682kB
array([[42.19    , 41.989998, 41.77    , ..., 36.92    , 36.71    ,
        36.78    ],
       [41.879997, 41.73    , 41.54    , ..., 37.67    , 37.35    ,
        37.37    ],
       [41.68    , 41.57    , 41.36    , ..., 38.54    , 38.16    ,
        38.129997],
       ...,
       [38.52    , 39.91    , 41.11    , ...,       nan,       nan,
              nan],
       [38.94    , 40.17    , 41.14    , ...,       nan,       nan,
              nan],
       [39.719997, 40.62    , 41.27    , ...,       nan,       nan,
              nan]], dtype=float32)
Coordinates:
    band         int64 8B 1
  * x            (x) float64 3kB 5e+05 5e+05 5.001e+05 ... 5.106e+05 5.106e+05
  * y            (y) float64 4kB 4.405e+06 4.405e+06 ... 4.39e+06 4.39e+06
    spatial_ref  int64 8B 0
Attributes: (12/34)
    ACCODE:                    Lasrc
    arop_ave_xshift(meters):   0
    arop_ave_yshift(meters):   0
    arop_ncp:                  0
    arop_rmse(meters):         0
    arop_s2_refimg:            NONE
    ...                        ...
    TIRS_SSM_POSITION_STATUS:  ESTIMATED
    ULX:                       499980
    ULY:                       4500000
    unit:                      Celsius
    USGS_SOFTWARE:             LPGS_16.3.0
    AREA_OR_POINT:             Area

<xarray.DataArray (y: 480, x: 355)> Size: 682kB
array([[0.2672    , 0.25149998, 0.2103    , ..., 0.2189    , 0.2049    ,
        0.2069    ],
       [0.25      , 0.2653    , 0.22289999, ..., 0.23359999, 0.212     ,
        0.20529999],
       [0.2452    , 0.2672    , 0.22659999, ..., 0.28489998, 0.2633    ,
        0.226     ],
       ...,
       [0.2916    , 0.2496    , 0.2547    , ...,        nan,        nan,
               nan],
       [0.23539999, 0.2262    , 0.2581    , ...,        nan,        nan,
               nan],
       [0.2146    , 0.22999999, 0.2461    , ...,        nan,        nan,
               nan]], dtype=float32)
Coordinates:
    band         int64 8B 1
  * x            (x) float64 3kB 5e+05 5e+05 5.001e+05 ... 5.106e+05 5.106e+05
  * y            (y) float64 4kB 4.405e+06 4.405e+06 ... 4.39e+06 4.39e+06
    spatial_ref  int64 8B 0
Attributes: (12/33)
    ACCODE:                    Lasrc
    arop_ave_xshift(meters):   0
    arop_ave_yshift(meters):   0
    arop_ncp:                  0
    arop_rmse(meters):         0
    arop_s2_refimg:            NONE
    ...                        ...
    TIRS_SSM_MODEL:            FINAL
    TIRS_SSM_POSITION_STATUS:  ESTIMATED
    ULX:                       499980
    ULY:                       4500000
    USGS_SOFTWARE:             LPGS_16.3.0
    AREA_OR_POINT:             Area

<xarray.DataArray (y: 480, x: 355)> Size: 682kB
array([[0.1452    , 0.1408    , 0.1281    , ..., 0.0786    , 0.0727    ,
        0.0722    ],
       [0.1437    , 0.1432    , 0.1325    , ..., 0.1103    , 0.0799    ,
        0.0727    ],
       [0.14999999, 0.1428    , 0.1312    , ..., 0.1512    , 0.1269    ,
        0.10439999],
       ...,
       [0.11      , 0.097     , 0.1313    , ...,        nan,        nan,
               nan],
       [0.0782    , 0.09079999, 0.1415    , ...,        nan,        nan,
               nan],
       [0.081     , 0.1105    , 0.1461    , ...,        nan,        nan,
               nan]], dtype=float32)
Coordinates:
    band         int64 8B 1
  * x            (x) float64 3kB 5e+05 5e+05 5.001e+05 ... 5.106e+05 5.106e+05
  * y            (y) float64 4kB 4.405e+06 4.405e+06 ... 4.39e+06 4.39e+06
    spatial_ref  int64 8B 0
Attributes: (12/33)
    ACCODE:                    Lasrc
    arop_ave_xshift(meters):   0
    arop_ave_yshift(meters):   0
    arop_ncp:                  0
    arop_rmse(meters):         0
    arop_s2_refimg:            NONE
    ...                        ...
    TIRS_SSM_MODEL:            FINAL
    TIRS_SSM_POSITION_STATUS:  ESTIMATED
    ULX:                       499980
    ULY:                       4500000
    USGS_SOFTWARE:             LPGS_16.3.0
    AREA_OR_POINT:             Area

<xarray.DataArray (y: 480, x: 355)> Size: 682kB
array([[0.1183    , 0.109     , 0.0981    , ..., 0.0457    , 0.042     ,
        0.0404    ],
       [0.11449999, 0.1076    , 0.1032    , ..., 0.0737    , 0.0454    ,
        0.0344    ],
       [0.11849999, 0.1182    , 0.1016    , ..., 0.1081    , 0.08199999,
        0.0627    ],
       ...,
       [0.07759999, 0.0663    , 0.096     , ...,        nan,        nan,
               nan],
       [0.0416    , 0.0636    , 0.1092    , ...,        nan,        nan,
               nan],
       [0.0439    , 0.07      , 0.1158    , ...,        nan,        nan,
               nan]], dtype=float32)
Coordinates:
    band         int64 8B 1
  * x            (x) float64 3kB 5e+05 5e+05 5.001e+05 ... 5.106e+05 5.106e+05
  * y            (y) float64 4kB 4.405e+06 4.405e+06 ... 4.39e+06 4.39e+06
    spatial_ref  int64 8B 0
Attributes: (12/33)
    ACCODE:                    Lasrc
    arop_ave_xshift(meters):   0
    arop_ave_yshift(meters):   0
    arop_ncp:                  0
    arop_rmse(meters):         0
    arop_s2_refimg:            NONE
    ...                        ...
    TIRS_SSM_MODEL:            FINAL
    TIRS_SSM_POSITION_STATUS:  ESTIMATED
    ULX:                       499980
    ULY:                       4500000
    USGS_SOFTWARE:             LPGS_16.3.0
    AREA_OR_POINT:             Area

<xarray.DataArray (y: 480, x: 355)> Size: 682kB
array([[42.07    , 41.76    , 40.95    , ..., 36.12    , 35.52    ,
        35.94    ],
       [41.62    , 41.18    , 40.34    , ..., 36.57    , 36.36    ,
        36.84    ],
       [41.2     , 40.649998, 39.84    , ..., 37.29    , 37.03    ,
        37.25    ],
       ...,
       [37.899998, 38.93    , 39.629997, ...,       nan,       nan,
              nan],
       [38.14    , 39.01    , 39.7     , ...,       nan,       nan,
              nan],
       [38.5     , 39.2     , 39.829998, ...,       nan,       nan,
              nan]], dtype=float32)
Coordinates:
    band         int64 8B 1
  * x            (x) float64 3kB 5e+05 5e+05 5.001e+05 ... 5.106e+05 5.106e+05
  * y            (y) float64 4kB 4.405e+06 4.405e+06 ... 4.39e+06 4.39e+06
    spatial_ref  int64 8B 0
Attributes: (12/34)
    ACCODE:                    Lasrc
    arop_ave_xshift(meters):   0
    arop_ave_yshift(meters):   0
    arop_ncp:                  0
    arop_rmse(meters):         0
    arop_s2_refimg:            NONE
    ...                        ...
    TIRS_SSM_POSITION_STATUS:  ESTIMATED
    ULX:                       499980
    ULY:                       4500000
    unit:                      Celsius
    USGS_SOFTWARE:             LPGS_16.3.0
    AREA_OR_POINT:             Area

<xarray.DataArray (y: 480, x: 355)> Size: 682kB
array([[0.109 , 0.0957, 0.0867, ..., 0.042 , 0.0399, 0.0362],
       [0.1006, 0.0933, 0.0906, ..., 0.064 , 0.0403, 0.0282],
       [0.1094, 0.1055, 0.0881, ..., 0.0935, 0.0681, 0.0494],
       ...,
       [0.0677, 0.0551, 0.0812, ...,    nan,    nan,    nan],
       [0.0329, 0.052 , 0.0931, ...,    nan,    nan,    nan],
       [0.0299, 0.0572, 0.1002, ...,    nan,    nan,    nan]],
      dtype=float32)
Coordinates:
    band         int64 8B 1
  * x            (x) float64 3kB 5e+05 5e+05 5.001e+05 ... 5.106e+05 5.106e+05
  * y            (y) float64 4kB 4.405e+06 4.405e+06 ... 4.39e+06 4.39e+06
    spatial_ref  int64 8B 0
Attributes: (12/33)
    ACCODE:                    Lasrc
    arop_ave_xshift(meters):   0
    arop_ave_yshift(meters):   0
    arop_ncp:                  0
    arop_rmse(meters):         0
    arop_s2_refimg:            NONE
    ...                        ...
    TIRS_SSM_MODEL:            FINAL
    TIRS_SSM_POSITION_STATUS:  ESTIMATED
    ULX:                       499980
    ULY:                       4500000
    USGS_SOFTWARE:             LPGS_16.3.0
    AREA_OR_POINT:             Area

<xarray.DataArray (y: 480, x: 355)> Size: 682kB
array([[ 64.,  64., 128., ...,  64.,  64., 128.],
       [ 64.,  64., 128., ...,  64., 128., 128.],
       [ 64.,  64.,  64., ..., 128., 128., 128.],
       ...,
       [128., 128., 128., ...,  nan,  nan,  nan],
       [128., 128., 128., ...,  nan,  nan,  nan],
       [192., 192., 128., ...,  nan,  nan,  nan]], dtype=float32)
Coordinates:
    band         int64 8B 1
  * x            (x) float64 3kB 5e+05 5e+05 5.001e+05 ... 5.106e+05 5.106e+05
  * y            (y) float64 4kB 4.405e+06 4.405e+06 ... 4.39e+06 4.39e+06
    spatial_ref  int64 8B 0
Attributes: (12/33)
    ACCODE:                    Lasrc
    arop_ave_xshift(meters):   0
    arop_ave_yshift(meters):   0
    arop_ncp:                  0
    arop_rmse(meters):         0
    arop_s2_refimg:            NONE
    ...                        ...
    TIRS_SSM_MODEL:            FINAL
    TIRS_SSM_POSITION_STATUS:  ESTIMATED
    ULX:                       499980
    ULY:                       4500000
    USGS_SOFTWARE:             LPGS_16.3.0
    AREA_OR_POINT:             Area

<xarray.DataArray (y: 480, x: 355)> Size: 682kB
array([[0.17009999, 0.1639    , 0.1476    , ..., 0.0639    , 0.0508    ,
        0.0539    ],
       [0.1612    , 0.16659999, 0.1541    , ..., 0.10879999, 0.0643    ,
        0.0577    ],
       [0.1871    , 0.1724    , 0.1489    , ..., 0.169     , 0.13239999,
        0.1052    ],
       ...,
       [0.1257    , 0.1103    , 0.15789999, ...,        nan,        nan,
               nan],
       [0.0809    , 0.1021    , 0.17119999, ...,        nan,        nan,
               nan],
       [0.0858    , 0.1199    , 0.16759999, ...,        nan,        nan,
               nan]], dtype=float32)
Coordinates:
    band         int64 8B 1
  * x            (x) float64 3kB 5e+05 5e+05 5.001e+05 ... 5.106e+05 5.106e+05
  * y            (y) float64 4kB 4.405e+06 4.405e+06 ... 4.39e+06 4.39e+06
    spatial_ref  int64 8B 0
Attributes: (12/33)
    ACCODE:                    Lasrc
    arop_ave_xshift(meters):   0
    arop_ave_yshift(meters):   0
    arop_ncp:                  0
    arop_rmse(meters):         0
    arop_s2_refimg:            NONE
    ...                        ...
    TIRS_SSM_MODEL:            FINAL
    TIRS_SSM_POSITION_STATUS:  ESTIMATED
    ULX:                       499980
    ULY:                       4500000
    USGS_SOFTWARE:             LPGS_16.3.0
    AREA_OR_POINT:             Area

<xarray.DataArray (y: 480, x: 355)> Size: 682kB
array([[0.0022, 0.0022, 0.002 , ..., 0.0013, 0.0015, 0.0015],
       [0.0021, 0.0022, 0.002 , ..., 0.0016, 0.0019, 0.0017],
       [0.002 , 0.002 , 0.0018, ..., 0.0017, 0.0017, 0.0014],
       ...,
       [0.0016, 0.0017, 0.0013, ...,    nan,    nan,    nan],
       [0.0017, 0.0015, 0.0014, ...,    nan,    nan,    nan],
       [0.0014, 0.0015, 0.0014, ...,    nan,    nan,    nan]],
      dtype=float32)
Coordinates:
    band         int64 8B 1
  * x            (x) float64 3kB 5e+05 5e+05 5.001e+05 ... 5.106e+05 5.106e+05
  * y            (y) float64 4kB 4.405e+06 4.405e+06 ... 4.39e+06 4.39e+06
    spatial_ref  int64 8B 0
Attributes: (12/33)
    ACCODE:                    Lasrc
    arop_ave_xshift(meters):   0
    arop_ave_yshift(meters):   0
    arop_ncp:                  0
    arop_rmse(meters):         0
    arop_s2_refimg:            NONE
    ...                        ...
    TIRS_SSM_MODEL:            FINAL
    TIRS_SSM_POSITION_STATUS:  ESTIMATED
    ULX:                       499980
    ULY:                       4500000
    USGS_SOFTWARE:             LPGS_16.3.0
    AREA_OR_POINT:             Area

<xarray.DataArray (y: 480, x: 355)> Size: 682kB
array([[0.26639998, 0.2543    , 0.2069    , ..., 0.1222    , 0.1028    ,
        0.1111    ],
       [0.24589999, 0.26389998, 0.2214    , ..., 0.1637    , 0.1217    ,
        0.1205    ],
       [0.2223    , 0.2509    , 0.2232    , ..., 0.2392    , 0.2017    ,
        0.1648    ],
       ...,
       [0.2131    , 0.18779999, 0.2201    , ...,        nan,        nan,
               nan],
       [0.1626    , 0.17009999, 0.2226    , ...,        nan,        nan,
               nan],
       [0.1469    , 0.1849    , 0.2201    , ...,        nan,        nan,
               nan]], dtype=float32)
Coordinates:
    band         int64 8B 1
  * x            (x) float64 3kB 5e+05 5e+05 5.001e+05 ... 5.106e+05 5.106e+05
  * y            (y) float64 4kB 4.405e+06 4.405e+06 ... 4.39e+06 4.39e+06
    spatial_ref  int64 8B 0
Attributes: (12/33)
    ACCODE:                    Lasrc
    arop_ave_xshift(meters):   0
    arop_ave_yshift(meters):   0
    arop_ncp:                  0
    arop_rmse(meters):         0
    arop_s2_refimg:            NONE
    ...                        ...
    TIRS_SSM_MODEL:            FINAL
    TIRS_SSM_POSITION_STATUS:  ESTIMATED
    ULX:                       499980
    ULY:                       4500000
    USGS_SOFTWARE:             LPGS_16.3.0
    AREA_OR_POINT:             Area

Now you are ready to run your code repeatedly on each raster you want to
load. To do this, we’ll use a structure called a `for` loop, which runs
the same code repeatedly with different variable values. The values that
change are special variables called **looping variables**.

To set up a `for` loop, you can use the following process:

1.  Copy the code you’re using into the `for` loop shell, making sure to
    indent it so Python knows it is part of the loop.
2.  Identify any variables that are **too specific**. For example, if I
    called a `DataArray` `green_da`, but the loop will be processing
    data from other bands…I might change the name to `da` whereever it
    appears.
3.  Identify the **looping variable(s)** and make sure they match your
    code.
4.  Establish an **accumulator** – a data structure to store the result.
    Add what you want to keep from each iteration of the loop to it.
5.  Write some code to test your loop, such as by printing out an
    intermediate value in the loop, or eventually plotting the final
    results. We recommend going line by line when you’re just getting
    started. This usually involves commenting code later on, and
    modifying the accumulator and testing as you go. You can also use
    the `break` keywork to stop the loop after a single iteration for
    testing.

<link rel="stylesheet" type="text/css" href="./assets/styles.css"><div class="callout callout-style-default callout-titled callout-task"><div class="callout-header"><div class="callout-icon-container"><i class="callout-icon"></i></div><div class="callout-title-container flex-fill">Try It: Process data</div></div><div class="callout-body-container callout-body"><p>Process all your bands. We’ve provided the structure of the
<code>for</code> loop – you will need to call your functions and work
out how to pass them the arguments they need.</p>
<p>Something that is tricky about looping through
<code>DataFrame</code>s is that they tend to wrap values in external
structures like <code>Series</code> (which are the data type of columns
in a <code>DataFrame</code>). The print out of a <code>Series</code>
containing one value and the print out of that value are not identical,
but the are <strong>very similar</strong>. To get a
<strong>value</strong> out from inside a <code>Series</code>, you can
add the following code: <code>.values[0]</code>. This will first remove
the <code>Series</code> wrapper, leaving an array, and the get the first
value in the array.</p></div></div>

In [ ]:
# Labels for each band to process
bands = {
    'B01': 'aerosol',
    'B02': 'red',
    'B03': 'green',
    'B04': 'blue',
    'B05': 'nir',
    'B06': 'swir1',
    'B07': 'swir2',
    'B09': 'cirrus',
    'B10': 'thermalir1',
    'B11': 'thermalir2'
}
# Initialize structure for saving images
denver_das = {band_name: [] for band_name in bands.values()}

for tile_id, tile_df in raster_df.groupby('tile_id'):
    # Load the cloud mask
    cloud_mask = process_cloud_mask(cloud_path, bits_to_mask) # cloud_path is coming from raster_df.Filename

    for band_id, row in tile_df.groupby('band_id'):
        if band_id in bands:
            band_name = bands[band_id]
            # Process band
            
            # Mask band
            
            
            # Store the resulting DataArray ofr later
            denver_das[band_name].append(band_masked_da)

# Merge all tiles
denver_das = {
    band_name: merge_arrays(das) 
    for band_name, das in denver_das.items()
}

denver_das['green'].plot(cmap='Greens', robust=True)

In [14]:
# ORIGINAL

# Labels for each band to process
bands = {
    'B01': 'aerosol',
    'B02': 'red',
    'B03': 'green',
    'B04': 'blue',
    'B05': 'nir',
    'B06': 'swir1',
    'B07': 'swir2',
    'B09': 'cirrus',
    'B10': 'thermalir1',
    'B11': 'thermalir2'
}
# Initialize structure for saving images
denver_das = {band_name: [] for band_name in bands.values()}

for tile_id, tile_df in raster_df.groupby('tile_id'):
    # Load the cloud mask
    cloud_mask = process_cloud_mask(cloud_path, bits_to_mask) # cloud_path is coming from raster_df.Filename

    for band_id, row in tile_df.groupby('band_id'):
        if band_id in bands:
            band_name = bands[band_id]
            # Process band
            
            # Mask band with cloud
            
            
            # Store the resulting DataArray ofr later
            denver_das[band_name].append(band_masked_da)

# Merge all tiles
denver_das = {
    band_name: merge_arrays(das) 
    for band_name, das in denver_das.items()
}

denver_das['green'].plot(cmap='Greens', robust=True)

<link rel="stylesheet" type="text/css" href="./assets/styles.css"><div class="callout callout-style-default callout-titled callout-task"><div class="callout-header"><div class="callout-icon-container"><i class="callout-icon"></i></div><div class="callout-title-container flex-fill">Try It: Check your data</div></div><div class="callout-body-container callout-body"><p>Make a plot of one of your merged bands with the denver boundary
superimposed. You should now have data for the whole city!</p></div></div>

In [16]:
# Plot a merged raster band
